# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    gym(export_method: "ad-hoc")
    build_app(workspace: "DemoApp.xcworkspace", scheme: "DemoApp")
    #upload_to_testflight

    appcenter_upload(
      api_token: "e6c1edcb9603a673e535f13d0354f7b69b60f205",
      owner_name: "nitesh.meshram@v2solutions.com",
      app_name: "DemoApp",
      ipa: "./DemoApp.ipa",
      notify_testers: true 
    )
   
  end
end