# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    gym(export_method: "ad-hoc")
    build_app(workspace: "DemoApp.xcworkspace", scheme: "DemoApp")
    #upload_to_testflight
    
    hockey(
      api_token: "9a172758bdfe4fe4b10299bfc9ea519a",
      ipa: "./DemoApp.ipa",
      notes: "Changelog"
    )
   
  end
end